# Generated by Django 4.2.16 on 2024-11-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
